---
# productivity.yml
# Group definition for productivity applications
# Install with: make install GROUP=productivity

group_name: "Productivity"
description: "Productivity tools collection (installs obsidian and proton groups)"
requires:
  - core
  - obsidian
  - proton

packages:
  nix: []
  flatpak: []
  pipx: []
  cargo: []
  npm: []
  apt: []

conditional: []

post_install_message: |
  Productivity suite installed.
  Includes: Obsidian (notes), Proton Pass (password manager)
